FROM node:12.13.1

ARG WORK_DIR=/usr/src/movie-app-client
ENV PATH ${WORK_DIR}/node_modules/.bin:$PATH

RUN mkdir -p ${WORK_DIR}
WORKDIR ${WORK_DIR}

COPY package.json ${WORK_DIR}

CMD ["/usr/src/movie-app-client/start.sh"]